//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;

    public partial class Group
    {
        public Group()
        {
            this.GroupByPhysios = new HashSet<GroupByPhysio>();
        }

        public int Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsUse { get; set; }

        public virtual ICollection<GroupByPhysio> GroupByPhysios { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
