//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;

    public partial class Transaction
    {
        public Transaction()
        {
            this.DeleteLogs = new HashSet<DeleteLog>();
            this.GroupByTransactions = new HashSet<GroupByTransaction>();
            this.Transaction1 = new HashSet<Transaction>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.UsePrePaidDebts = new HashSet<UsePrePaidDebt>();
            this.UsePrePaidDebts1 = new HashSet<UsePrePaidDebt>();
        }

        public string Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CounterId { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> TaxAmount { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<long> RecieveAmount { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> GiftCardId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> ServiceChages { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Consultantfees { get; set; }

        public virtual Counter Counter { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DeleteLog> DeleteLogs { get; set; }
        public virtual DoctorPhysio DoctorPhysio { get; set; }
        public virtual GiftCard GiftCard { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<GroupByTransaction> GroupByTransactions { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<Transaction> Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual ICollection<UsePrePaidDebt> UsePrePaidDebts { get; set; }
        public virtual ICollection<UsePrePaidDebt> UsePrePaidDebts1 { get; set; }
    }
}
