//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;

    public partial class DoctorPhysio
    {
        public DoctorPhysio()
        {
            this.GroupByPhysios = new HashSet<GroupByPhysio>();
            this.GroupByTransactions = new HashSet<GroupByTransaction>();
            this.Transactions = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        public Nullable<bool> IsDoctor { get; set; }
        public Nullable<int> ChargesPerPatient { get; set; }
        public Nullable<int> PhysicoCharges { get; set; }
        public Nullable<bool> IsInhouse { get; set; }
        public Nullable<decimal> ForPhysioTrain { get; set; }
        public string Name { get; set; }
        public string Degree { get; set; }
        public string Specialisation { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsPercent { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Percent { get; set; }

        public Nullable<long> TotalAmount { get; set; }

        public int TempStaffId { get; set; }
        public string Shift { get; set; }
        public int DutyId { get; set; }

        public virtual ICollection<GroupByPhysio> GroupByPhysios { get; set; }
        public virtual ICollection<GroupByTransaction> GroupByTransactions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
