//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    
    public partial class Top100SaleItemList_Result
    {
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal DisCount { get; set; }
        public Nullable<long> UnitPrice { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<long> ItemTotalAmount { get; set; }
    }
}
