//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    
    public partial class GetDoctorFeesByDateRate_Result
    {
        public Nullable<decimal> Injection { get; set; }
        public Nullable<decimal> Physio { get; set; }
        public Nullable<decimal> XRay { get; set; }
        public string Name { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> Consultantfees { get; set; }
    }
}
