//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public Expense()
        {
            this.ExpenseDetails = new HashSet<ExpenseDetail>();
        }
    
        public int Id { get; set; }
        public string ExpenseNo { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<decimal> TotalExpenseAmount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ExpenseCategoryId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ExpenseDetail> ExpenseDetails { get; set; }
    }
}
