//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;

    public partial class DailyDutyPhysio
    {
        public int Id { get; set; }
        public string StaffID { get; set; }
        public System.DateTime DutyDate { get; set; }
        public string Shift { get; set; }
        public Nullable<int> GroupID { get; set; }

        public Nullable<long> TotalAmout { get; set; }
    }
}
